### ISSUE TITLE
Prefermentos

### ISSUE THREAD

**Issue by aaramirez** [synergyvision/formulapanadera#9]
- [x] Ofrecer la opción de agregar un prefermento a una fórmula de un pan, lo cual implica seleccionar los ingredientes y la proporción de cada ingrediente.
- [x] Considerar como parámetro la cantidad adicional en la preparación para la producción (Factor de compensación de pérdidas por evaporación).
- [x] Permitir agregar el procedimiento de elaboración del prefermento.
- [x] Permitir la clonación de un prefermento para modificar las proporciones. Considerar dos decimales en la fórmula de los ingredientes del prefermento.
- [x] Agregar como parámetro la sugerencia del rango de valores sugeridos para la incorporación de un prefermento en una fórmula.

**Comment by albasanchez** [comment]
Agregados los prefermentos, asi como
- Prefermentos con masa madre
- Ingredientes compuestos de otros ingredientes
- Rellenos y glaseados
